services:
  nginx:
    container_name: tournament_nginx
    restart: on-failure:1
    build: ./docker/nginx
    volumes:
      - ./docker/nginx/sites-enabled:/etc/nginx/sites-enabled:cached
      - ./app:/var/www/project
    ports:
      - '80:80'
    depends_on:
      - app
      - mysql
  mysql:
    restart: on-failure:3
    container_name: tournaments-mysql
    image: mysql/mysql-server:latest
    environment:
      TZ: 'Europe/Moscow'
      MYSQL_ROOT_PASSWORD: '123123'
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./docker/mysql/db.sql:/docker-entrypoint-initdb.d/db.sql
      - ./docker/mysql/my.cnf:/etc/my.cnf:cached
    ports:
      - '3306:3306'
  app:
    container_name: tournaments
    build: ./docker/php
    volumes:
      - ./app:/app
    depends_on:
      - mysql